### ISSUE TITLE
Create Chat GPT Training Data CPSC 455

### ISSUE THREAD

**Issue by kylexrich** [kylexrich/coursegpt#18]
https://cpsc4552023.slack.com/archives/C057LLJHBG9/p1684527306771369

https://cpsc4552023.slack.com/archives/C057LLJHBG9/p1684088568318859

https://platform.openai.com/docs/guides/fine-tuning

**Comment by kylexrich** [comment]
@duffydu  if you get bored with this, please feel free to let me know! I can easily take over, and you can take on some more interesting (less tedious) tasks.

Just want to make sure you are good :D

**Comment by duffydu** [comment]
Marking this as done so far as all files from the course website are properly prepared and uploaded to a private [google drive folder](https://drive.google.com/drive/folders/1YUYZjiEYKBp8a_vvUSAc1DnWvps9v_y9?usp=drive_link) shared amongst teammates.

Next steps of adding more course relevant content to be used for further training the model will be done later down the road.
