### ISSUE TITLE
[May 28, 2023] Scrum Update

### ISSUE THREAD

**Issue by kylexrich** [kylexrich/coursegpt#38]

**Comment by huangcar1** [comment]
**Name:** Carolyn Huang (m5y3w)

**1. What did you work on this past iteration (2 weeks)?** 
I mostly worked on finishing some API stuff (part of [this PR](https://github.com/kylexrich/coursegpt/pull/23)) and created basic CRUD outlines for each template

**2. What were any major issues/challenges you ran into?** 
Nothing really! No blockers for me 

**3. What do you plan to work on for this coming iteration (2 weeks)?** 
I'm planning on working on the backend components for schools and courses (incl. populating the database with some initial data and all of the other necessary logic). If I have time, I'll also be working on both the front end and back end components of our feedback element, where users can create positive/negative feedback based on if the answer provided to a question was relevant and factual

**Comment by kylexrich** [comment]
**1. What did you work on this past iteration (2 weeks)?**  
- [Setup MERN Project Structure](https://github.com/kylexrich/coursegpt/commit/dcb8051a44a11c53a1fff569af727f0b0f157ccd) & Github project to track tasks
- [Created Database Schema](https://github.com/kylexrich/coursegpt/issues/7)
- Created Project Progress 1 w/ Team
- [Created User & Message API's & Controller Template](https://github.com/kylexrich/coursegpt/issues/20) 
- Heroku CD Setup (Push to Main-->Deployed)
- [Connected to MongoDB](https://github.com/kylexrich/coursegpt/issues/25)
- [Setup simple structure for making calls to the Open AI API](https://github.com/kylexrich/coursegpt/issues/17)

**2. What were any major issues/challenges you ran into?**  
Forgot many details of full stack development! Had some struggles, accordingly.
- Doubled endpoints (for example, /api/users/api/users)
- npm dotenv configuration issues
- Heroku deployment process
- eslint config (ugh)

**3. What do you plan to work on for this coming iteration (2 weeks)?**  
- Depending on who gets to it first, possibly setting up redux
- [Developing the User Registration/Login controllers](https://github.com/kylexrich/coursegpt/issues/11)
- [Developing the Login/Signup components](https://github.com/kylexrich/coursegpt/issues/26)

**Comment by ajo01** [comment]
**Name: Amy Jo**


**1. What did you work on this past iteration (2 weeks)?**
I made the Figma prototypes and implemented the majority of the UI for our main chat page. See #34 & #35.

**2. What were any major issues/challenges you ran into?** 
No blockers.

**3. What do you plan to work on for this coming iteration (2 weeks)?**
I'm taking on #28 - making the actual chat interface where CourseGPT answers the users' prompts. I hope to also start making the chat controller in the backend with #12 .

**Comment by duffydu** [comment]
Name: Duffy Du (f4r3h)

1. What did you work on this past iteration (2 weeks)?
- exploredthe openAI API documentation and other resources for the chatGPT fine-tuning process
- prepared and cleaned CPSC455 course data for prompt generation ([#18](https://github.com/kylexrich/coursegpt/issues/18))

2. What were any major issues/challenges you ran into?
- preparing data has been a very tedious and manual process especially with some slides having pictures of code which needs to be manually retyped out to feed into chatGPT for prompt generation.
- recently discovered embeddings which seem to be a better training method than the fine-tuing method for our specific use case --> planning to have a discussion during our team meeting on Tuesday 

3. What do you plan to work on for this coming iteration (2 weeks)?
- Continue to prepare data for prompt generation ([#18](https://github.com/kylexrich/coursegpt/issues/18))
- Continue to refine prompts
- Try training a model through the openAI CLI 
- Pick up another issue if I have time

**Comment by ritikk7** [comment]
Name: Ritik Keswani (l6v5i)

1. What did you work on this past iteration (2 weeks)?
So far I've worked on project ideation, setting up team workflow and generating frontend tickets with the rest of team.

3. What were any major issues/challenges you ran into?
No blockers for me for now!

4. What do you plan to work on for this coming iteration (2 weeks)?
I'll be working on creating the frontend and backend of the profile page for our app and pick up any more tickets as needed.
