### ISSUE TITLE
[June 11, 2023] Scrum Update

### ISSUE THREAD

**Issue by huangcar1** [kylexrich/coursegpt#48]
Describe (for the project): 

1. what you’ve worked on in the previous two weeks, 
2. what you’ll be working on in the next two weeks, 
3. where you might have gotten stuck during the last two weeks. 

(~1 sentence per three items; expand on at least 1 item for full participation marks)

**Comment by ajo01** [comment]
Name: Amy Jo (k4y2b)

1. what you’ve worked on in the previous two weeks
- chat messaging frontend was finished
- started planning for how to implement chat controller 

2. what you’ll be working on in the next two weeks
- chat controller in the backend so messaging will work end to end #40 
- potentially pick up another ticket

3. where you might have gotten stuck during the last two weeks
- I've been working on the frontend past 2 sprints so i'm not familiar with what the backend looks like right now. Pair programming with a team member to figure it out

**Comment by huangcar1** [comment]
Name: Carolyn Huang (m5y3w)

1. what you’ve worked on in the previous two weeks
- started and finished school/course controller (frontend and backend)

2. what you’ll be working on in the next two weeks
- working on the like/dislike messaging
- hopefully another ticket too depending on if i get blocked or not

3. where you might have gotten stuck during the last two weeks
- Nothing really - redux was a bit to get used to at first, but I figured it out eventually! Also, I had to change a couple of the API endpoints in the middle of coding, so I guess that's just a sign that I should probably plan out how I want to approach things a bit better before I start on them.

**Comment by duffydu** [comment]
Name: Duffy Du (f4r3h)

**1. What did you work on this past iteration (2 weeks)?**

-  After the team discussion on switching the training method from fine tuning to embeddings, explored the [openAI cookbook](https://github.com/openai/openai-cookbook/tree/main) on the details of how embeddings are done. 
- Prepared and cleaned all course website data to allow proper sectioning for generating embeddings
- Attempted and successfully created embeddings for course website data and used embedding based search to query chatGPT. The model currently is able to answer questions that are within the scope of course website with great accuracy.

**2. What were any major issues/challenges you ran into?**
- Again, the process of preparing and cleaning data to be ready for embeddings generation has been a very tedious and manual process. In the future, hopefully we can automate this process to make it more streamlined from the uploading source document to the fully trained model.

**3. What do you plan to work on for this coming iteration (2 weeks)?**
- All the training so far are all done in a jupyter notebook with Python. The next step is to explore the openAI node.js library and see if we can incorporate the python code with our existing MERN stack project.
- After that, the next step would be connecting the frontend chat UI with querying our trained model

**Comment by kylexrich** [comment]
Kyle Rich h7w2b

1. What did you work on this past iteration (2 weeks)?
- Fully implemented the user registration and login flow using cookie based jwt, as well as google authentication. This way, users can sign in, close the browser, etc, and remain authenticated until either their tokens expire, or they specifically log out of the application. See https://github.com/kylexrich/coursegpt/pull/41

- Alongside help from Carolyn, almost finished fully implementing our redux slices to more easily manage frontend development. This includes an authSlice to manage user authentication, userSlice for basic user data, message and chatSlices to manage the chats, as well as school and courseSlices to manage schools. See https://github.com/kylexrich/coursegpt/tree/refactoring

2. What were any major issues/challenges you ran into?
The biggest challenge was setting up the user registration and login flow using cookie based jwt, as well as google authentication. More specifically, I struggled for a long time trying to figure out how I could make everything work both during development, as well as in production. 

3. What do you plan to work on for this coming iteration (2 weeks)?
- Finish implementing the redux slices and refactor much of our frontend to properly leverage the redux store.
- Now having a better idea of how data and information flows within our application, making improvements, deletions, and alterations to our API endpoints.

**Comment by ritikk7** [comment]
Name: Ritik Keswani (l6v5i)

1. What you’ve worked on in the previous two weeks
Worked on the ProfilePage component's frontend and started planning for the backend and future improvements to the frontend.

2. What you’ll be working on in the next two weeks
Will work on the ProfilePage backend and another ticket depending on what needs to be done.

3. Where you might have gotten stuck during the last two weeks
Figuring out the dataflow in the application and how different components connected to each other.
