### ISSUE TITLE
ask user for registration details (school and courses)

### ISSUE THREAD

**Issue by ajo01** [kylexrich/coursegpt#65]
See https://github.com/kylexrich/coursegpt/issues/65#issuecomment-1606136507

**Comment by kylexrich** [comment]
Love the first two! A note on the third: I personally think itd be nice to have a two step registration page for students. The first page can be the general info I already ask for, the second page could ask for the users school and courses they are currently taking. We can talk about it next meeting! Something like this? https://chakra-templates.dev/templates/forms/multistep/basic3StepForm

**Comment by ajo01** [comment]
I also considered getting users to choose which courses they wanted upon registration. Making all courses favorites by default would presumably require fewer code changes, which is why I suggested it, but I'd be happy with either of the two!

**Comment by duffydu** [comment]
Making a comment with all of the requirements in scope of this issue:

- [ ] Implement a two step registration process that resembles [this](https://chakra-templates.dev/templates/forms/multistep/basic3StepForm) 
Notes:
- First page: 
![image](https://github.com/kylexrich/coursegpt/assets/92617701/0c9a1768-aab3-449e-985b-2ec132389caf)
![image](https://github.com/kylexrich/coursegpt/assets/92617701/ca19c74e-0304-4898-b9e4-ebb7a6269e03)
- Second page:
![image](https://github.com/kylexrich/coursegpt/assets/92617701/4ffa7c24-c5ca-4c27-ab0a-c28e907ea34b)
Except with all the school and course information needed to set up this page:
![image](https://github.com/kylexrich/coursegpt/assets/92617701/1dfe2fc8-4833-4ecc-895a-5f775c30c5a8)

- [ ] Allow users to upload their own profile image.
Notes:
- Allow upload in both the registration process and the profile editing modal. 
- There will be a couple defaults to select from if user doesn't want to upload their own.

- [ ] Organize chats in the sidepanel by date (most recent first)

**Comment by duffydu** [comment]
After Tuesday team discussion, we decided to drop the profile upload feature for this issue for now because it is lower in priority and fits better as a part of ritik's profile modal.
